title: Digital Timing Recovery System with ML-based TED and Polyphase Filters
authors:
- Juan Chirino
- Tiago Ruiz
- Agustin Pesce
- Agustin Arese
- Juliana Maidana
type: Digital
tapeout_target: false
status_text: Proposed
