title: 2 GHz 4-Quadrant Phase Interpolator with 8x Network
authors:
- Agustina Trabichet
- Victor Muñoz
- Macarena Gonzalez
- Juana Pucheta Valentín Ramirez
- Pablo Dominguez
type: Analog
tapeout_target: true
status_text: ✅ Accepted
