title: UART Communication Interface for ALU
authors:
- Augusto Gabriel Cabrera
- Juan Ignacio Chirino Bohorquez
- Natalia Carolina Borbón
- Camila Planes
- Tiago Gastón Giaimis
type: Digital
tapeout_target: false
status_text: Proposed
