title: 8-bit Gated Ring Oscillator Time-to-Digital Converter
authors:
- Sebastian Hernandez
- Emiliano Marclé
- Constanza Abiuso
- Paula Brizzio
type: Digital
tapeout_target: true
status_text: ✅ Accepted
